#include <stdio.h>

void zero()
{
    printf("11111111 \n");
    printf("11    11 \n");
    printf("11    11 \n");
    printf("11    11 \n");
    printf("11    11 \n");
    printf("11    11 \n");
    printf("11    11 \n");
    printf("11111111 \n\n");
}

void one()
{
    printf("   11     \n");
    printf("   11     \n");
    printf("   11     \n");
    printf("   11     \n");
    printf("   11     \n");
    printf("   11     \n");
    printf("   11     \n");
    printf("   11   \n\n");
}
